<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_noUVYL44Eeuk4pNB4Zwu1A" name="Requests" author="andre" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_noUVYb44Eeuk4pNB4Zwu1A" name="Register Request">
      <elements xmi:type="process:Lane" xmi:id="_noUVYr44Eeuk4pNB4Zwu1A" name="Employee lane" actor="_tbi4QL44Eeuk4pNB4Zwu1A">
        <elements xmi:type="process:StartEvent" xmi:id="_noUVY744Eeuk4pNB4Zwu1A" name="Start1" outgoing="_uK0ZEL44Eeuk4pNB4Zwu1A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_noUVZL44Eeuk4pNB4Zwu1A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_noUVZb44Eeuk4pNB4Zwu1A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_noUVZr44Eeuk4pNB4Zwu1A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_tbi4Qb44Eeuk4pNB4Zwu1A" name="Preencher Pedido" outgoing="_vu5a8L44Eeuk4pNB4Zwu1A" incoming="_uK0ZEL44Eeuk4pNB4Zwu1A" actor="_tbi4QL44Eeuk4pNB4Zwu1A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tbi4Qr44Eeuk4pNB4Zwu1A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tbi4Q744Eeuk4pNB4Zwu1A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tbi4RL44Eeuk4pNB4Zwu1A" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_tbi4Rb44Eeuk4pNB4Zwu1A" documentation="Gets all client accounts from salesforce CRM" name="salesforceGetClientAccounts" definitionId="salesforce-querysobjects" event="ON_ENTER" definitionVersion="1.0.1">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_tbi4Rr44Eeuk4pNB4Zwu1A" definitionId="salesforce-querysobjects" version="1.0.1" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4R744Eeuk4pNB4Zwu1A" key="username">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4SL44Eeuk4pNB4Zwu1A" name="andre@ipl.com" content="andre@ipl.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4Sb44Eeuk4pNB4Zwu1A" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4Sr44Eeuk4pNB4Zwu1A" name="janela2012" content="janela2012" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4S744Eeuk4pNB4Zwu1A" key="securityToken">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4TL44Eeuk4pNB4Zwu1A" name="78HnE36tf0FEPzNFPjz7OEe2" content="78HnE36tf0FEPzNFPjz7OEe2" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4Tb44Eeuk4pNB4Zwu1A" key="authEndpoint">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4Tr44Eeuk4pNB4Zwu1A" name="https://login.salesforce.com/services/Soap/u/24.0" content="https://login.salesforce.com/services/Soap/u/24.0" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4T744Eeuk4pNB4Zwu1A" key="serviceEndpoint">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4UL44Eeuk4pNB4Zwu1A" name="https://login.salesforce.com/services/Soap/u/24.0" content="https://login.salesforce.com/services/Soap/u/24.0" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4Ub44Eeuk4pNB4Zwu1A" key="restEndpoint">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4Ur44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4U744Eeuk4pNB4Zwu1A" key="proxyHost">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4VL44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4Vb44Eeuk4pNB4Zwu1A" key="proxyPort">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4Vr44Eeuk4pNB4Zwu1A" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4V744Eeuk4pNB4Zwu1A" key="proxyUsername">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4WL44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4Wb44Eeuk4pNB4Zwu1A" key="proxyPassword">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4Wr44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4W744Eeuk4pNB4Zwu1A" key="connectionTimeout">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4XL44Eeuk4pNB4Zwu1A" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4Xb44Eeuk4pNB4Zwu1A" key="readTimeout">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4Xr44Eeuk4pNB4Zwu1A" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_tbi4X744Eeuk4pNB4Zwu1A" key="query">
                <expression xmi:type="expression:Expression" xmi:id="_tbi4YL44Eeuk4pNB4Zwu1A" name="&lt;pattern-expression>" content="SELECT name, accountNumber FROM ACCOUNT" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_tbi4Yb44Eeuk4pNB4Zwu1A">
              <leftOperand xmi:type="expression:Expression" xmi:id="_tbi4Yr44Eeuk4pNB4Zwu1A" name="clients" content="clients" type="TYPE_VARIABLE" returnType="java.util.List">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tbi4Y744Eeuk4pNB4Zwu1A" name="clients" multiple="true" dataType="_noUVlL44Eeuk4pNB4Zwu1A" className="com.prestaser.model.Client"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_tbi4ZL44Eeuk4pNB4Zwu1A" name="getClientAccountsScript()" content="import com.prestaser.model.Client&#xD;&#xA;import com.sforce.soap.partner.sobject.SObject&#xD;&#xA;&#xD;&#xA;ArrayList&lt;Client> accs = new ArrayList()&#xD;&#xA;&#xD;&#xA;SObject[] all = queryResults.getRecords()&#xD;&#xA;&#xD;&#xA;for  (SObject s in all){&#xD;&#xA;&#x9;Client a = new Client()&#xD;&#xA;&#x9;a.clientId = s.getId()&#xD;&#xA;&#x9;a.name = s.getField(&quot;Name&quot;)&#xD;&#xA;&#x9;accs.add(a)&#xD;&#xA;}&#xD;&#xA;return accs" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
                <referencedElements xmi:type="definition:Output" xmi:id="_tbi4Zb44Eeuk4pNB4Zwu1A" name="queryResults" type="com.sforce.soap.partner.QueryResult"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_tbi4Zr44Eeuk4pNB4Zwu1A" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_tbi4Z744Eeuk4pNB4Zwu1A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_tbi4aL44Eeuk4pNB4Zwu1A" name="request" content="request" type="TYPE_VARIABLE" returnType="com.prestaser.model.Request">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tbi4ab44Eeuk4pNB4Zwu1A" name="request" dataType="_noUVlL44Eeuk4pNB4Zwu1A" className="com.prestaser.model.Request"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_tbi4ar44Eeuk4pNB4Zwu1A" name="requestInput.requestDate" content="requestInput?.requestDate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDateTime">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_tbi4a744Eeuk4pNB4Zwu1A" name="requestInput" type="COMPLEX">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_tbi4bL44Eeuk4pNB4Zwu1A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_tbi4bb44Eeuk4pNB4Zwu1A" type="JAVA_METHOD" expression="setRequestDate">
              <inputTypes>java.time.LocalDateTime</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_tbi4br44Eeuk4pNB4Zwu1A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_tbi4b744Eeuk4pNB4Zwu1A" name="request" content="request" type="TYPE_VARIABLE" returnType="com.prestaser.model.Request">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tbi4cL44Eeuk4pNB4Zwu1A" name="request" dataType="_noUVlL44Eeuk4pNB4Zwu1A" className="com.prestaser.model.Request"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_tbi4cb44Eeuk4pNB4Zwu1A" name="requestInput.description" content="requestInput?.description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_tbi4cr44Eeuk4pNB4Zwu1A" name="requestInput" type="COMPLEX">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_tbi4c744Eeuk4pNB4Zwu1A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_tbi4dL44Eeuk4pNB4Zwu1A" type="JAVA_METHOD" expression="setDescription">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_tbi4db44Eeuk4pNB4Zwu1A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_tbi4dr44Eeuk4pNB4Zwu1A" name="request" content="request" type="TYPE_VARIABLE" returnType="com.prestaser.model.Request">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tbi4d744Eeuk4pNB4Zwu1A" name="request" dataType="_noUVlL44Eeuk4pNB4Zwu1A" className="com.prestaser.model.Request"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_tbi4eL44Eeuk4pNB4Zwu1A" name="requestInput.client" content="requestInput?.client" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.prestaser.model.Client">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_tbi4eb44Eeuk4pNB4Zwu1A" name="requestInput" type="COMPLEX">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_tbi4er44Eeuk4pNB4Zwu1A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_tbi4e744Eeuk4pNB4Zwu1A" type="JAVA_METHOD" expression="setClient">
              <inputTypes>com.prestaser.model.Client</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tbi4fL44Eeuk4pNB4Zwu1A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tbi4fb44Eeuk4pNB4Zwu1A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tbi4fr44Eeuk4pNB4Zwu1A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tbi4f744Eeuk4pNB4Zwu1A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tbi4gL44Eeuk4pNB4Zwu1A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_tbi4gb44Eeuk4pNB4Zwu1A">
            <targetForm xmi:type="expression:Expression" xmi:id="_tbi4gr44Eeuk4pNB4Zwu1A" name="fillRequest" content="c306b22b-7d96-4236-afff-f61f72252e58" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_tbi4g744Eeuk4pNB4Zwu1A">
            <inputs xmi:type="process:ContractInput" xmi:id="_tbi4hL44Eeuk4pNB4Zwu1A" name="requestInput" type="COMPLEX">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_tbi4hb44Eeuk4pNB4Zwu1A"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_tbi4hr44Eeuk4pNB4Zwu1A" name="requestDate" type="LOCALDATETIME">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_tbi4h744Eeuk4pNB4Zwu1A"/>
              </inputs>
              <inputs xmi:type="process:ContractInput" xmi:id="_tbi4iL44Eeuk4pNB4Zwu1A" name="description">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_tbi4ib44Eeuk4pNB4Zwu1A"/>
              </inputs>
              <inputs xmi:type="process:ContractInput" xmi:id="_tbi4ir44Eeuk4pNB4Zwu1A" name="client" type="COMPLEX">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_tbi4i744Eeuk4pNB4Zwu1A"/>
                <inputs xmi:type="process:ContractInput" xmi:id="_tbi4jL44Eeuk4pNB4Zwu1A" name="clientId">
                  <mapping xmi:type="process:ContractInputMapping" xmi:id="_tbi4jb44Eeuk4pNB4Zwu1A"/>
                </inputs>
                <inputs xmi:type="process:ContractInput" xmi:id="_tbi4jr44Eeuk4pNB4Zwu1A" name="name">
                  <mapping xmi:type="process:ContractInputMapping" xmi:id="_tbi4j744Eeuk4pNB4Zwu1A"/>
                </inputs>
              </inputs>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_tbi4kL44Eeuk4pNB4Zwu1A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_vKTgIL44Eeuk4pNB4Zwu1A" name="Pedido Preenchido" incoming="_vu5a8L44Eeuk4pNB4Zwu1A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vKTgIb44Eeuk4pNB4Zwu1A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vKTgIr44Eeuk4pNB4Zwu1A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vKTgI744Eeuk4pNB4Zwu1A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_0N-OUL44Eeuk4pNB4Zwu1A" name="clients" multiple="true" dataType="_noUVlL44Eeuk4pNB4Zwu1A" className="com.prestaser.model.Client">
        <defaultValue xmi:type="expression:Expression" xmi:id="_0N-OUb44Eeuk4pNB4Zwu1A" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_1C0LoL44Eeuk4pNB4Zwu1A" name="request" dataType="_noUVlL44Eeuk4pNB4Zwu1A" className="com.prestaser.model.Request">
        <defaultValue xmi:type="expression:Expression" xmi:id="_1C0Lob44Eeuk4pNB4Zwu1A" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_noUVdL44Eeuk4pNB4Zwu1A">
        <targetForm xmi:type="expression:Expression" xmi:id="_Qog8UL45Eeuk4pNB4Zwu1A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_noUVdr44Eeuk4pNB4Zwu1A">
        <targetForm xmi:type="expression:Expression" xmi:id="_noUVd744Eeuk4pNB4Zwu1A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uK0ZEL44Eeuk4pNB4Zwu1A" target="_tbi4Qb44Eeuk4pNB4Zwu1A" source="_noUVY744Eeuk4pNB4Zwu1A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uK0ZEb44Eeuk4pNB4Zwu1A"/>
        <condition xmi:type="expression:Expression" xmi:id="_uK0ZEr44Eeuk4pNB4Zwu1A" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vu5a8L44Eeuk4pNB4Zwu1A" target="_vKTgIL44Eeuk4pNB4Zwu1A" source="_tbi4Qb44Eeuk4pNB4Zwu1A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vu5a8b44Eeuk4pNB4Zwu1A"/>
        <condition xmi:type="expression:Expression" xmi:id="_vu5a8r44Eeuk4pNB4Zwu1A" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_tbi4QL44Eeuk4pNB4Zwu1A" name="Teste" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_noUVfL44Eeuk4pNB4Zwu1A"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_noUVfb44Eeuk4pNB4Zwu1A">
        <name xmi:type="expression:Expression" xmi:id="_noUVfr44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_noUVf744Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_noUVgL44Eeuk4pNB4Zwu1A">
        <name xmi:type="expression:Expression" xmi:id="_noUVgb44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_noUVgr44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_noUVg744Eeuk4pNB4Zwu1A">
        <name xmi:type="expression:Expression" xmi:id="_noUVhL44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_noUVhb44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_noUVhr44Eeuk4pNB4Zwu1A">
        <name xmi:type="expression:Expression" xmi:id="_noUVh744Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_noUViL44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_noUVib44Eeuk4pNB4Zwu1A">
        <name xmi:type="expression:Expression" xmi:id="_noUVir44Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_noUVi744Eeuk4pNB4Zwu1A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_noUVjL44Eeuk4pNB4Zwu1A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_noUVjb44Eeuk4pNB4Zwu1A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_noUVjr44Eeuk4pNB4Zwu1A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_noUVj744Eeuk4pNB4Zwu1A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_noUVkL44Eeuk4pNB4Zwu1A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_noUVkb44Eeuk4pNB4Zwu1A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_noUVkr44Eeuk4pNB4Zwu1A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_noUVk744Eeuk4pNB4Zwu1A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_noUVlL44Eeuk4pNB4Zwu1A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_noUVlb44Eeuk4pNB4Zwu1A" type="Process" element="_noUVYL44Eeuk4pNB4Zwu1A" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_noUVlr44Eeuk4pNB4Zwu1A" type="2007" element="_noUVYb44Eeuk4pNB4Zwu1A">
      <children xmi:type="notation:DecorationNode" xmi:id="_noUVl744Eeuk4pNB4Zwu1A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_noUVmL44Eeuk4pNB4Zwu1A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_noUVmb44Eeuk4pNB4Zwu1A" type="3007" element="_noUVYr44Eeuk4pNB4Zwu1A">
          <children xmi:type="notation:DecorationNode" xmi:id="_noUVmr44Eeuk4pNB4Zwu1A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_noUVm744Eeuk4pNB4Zwu1A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_noUVn744Eeuk4pNB4Zwu1A" type="3002" element="_noUVY744Eeuk4pNB4Zwu1A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_noUVoL44Eeuk4pNB4Zwu1A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_noUVob44Eeuk4pNB4Zwu1A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_noUVor44Eeuk4pNB4Zwu1A" x="62" y="134"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tbjfUL44Eeuk4pNB4Zwu1A" type="3005" element="_tbi4Qb44Eeuk4pNB4Zwu1A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tbjfUb44Eeuk4pNB4Zwu1A" type="5005" element="_tbi4Qb44Eeuk4pNB4Zwu1A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tbjfUr44Eeuk4pNB4Zwu1A" x="230" y="118" width="153" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vKUHML44Eeuk4pNB4Zwu1A" type="3062" element="_vKTgIL44Eeuk4pNB4Zwu1A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vKUHMb44Eeuk4pNB4Zwu1A" type="5090" element="_vKTgIL44Eeuk4pNB4Zwu1A">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vKUHMr44Eeuk4pNB4Zwu1A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vKUHM744Eeuk4pNB4Zwu1A" x="494" y="134"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_noUVo744Eeuk4pNB4Zwu1A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_noUVpL44Eeuk4pNB4Zwu1A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_noUVpb44Eeuk4pNB4Zwu1A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_noUVpr44Eeuk4pNB4Zwu1A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_noUVp744Eeuk4pNB4Zwu1A" x="53" y="10" width="1292" height="297"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_noUVqL44Eeuk4pNB4Zwu1A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_noUVqb44Eeuk4pNB4Zwu1A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_noUVqr44Eeuk4pNB4Zwu1A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_noUVq744Eeuk4pNB4Zwu1A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_noUVrL44Eeuk4pNB4Zwu1A" width="720" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_noUVrb44Eeuk4pNB4Zwu1A"/>
    <edges xmi:type="notation:Connector" xmi:id="_uK1AIL44Eeuk4pNB4Zwu1A" type="4001" element="_uK0ZEL44Eeuk4pNB4Zwu1A" source="_noUVn744Eeuk4pNB4Zwu1A" target="_tbjfUL44Eeuk4pNB4Zwu1A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uK1AI744Eeuk4pNB4Zwu1A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uK1AJL44Eeuk4pNB4Zwu1A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uK1AIb44Eeuk4pNB4Zwu1A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uK1AIr44Eeuk4pNB4Zwu1A" points="[-6, -2, -513, -92]$[486, 84, -21, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uK2OQL44Eeuk4pNB4Zwu1A" id="(1.0,0.9)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uK2OQb44Eeuk4pNB4Zwu1A" id="(0.13725490196078433,0.3157894736842105)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vu6CAL44Eeuk4pNB4Zwu1A" type="4001" element="_vu5a8L44Eeuk4pNB4Zwu1A" source="_tbjfUL44Eeuk4pNB4Zwu1A" target="_vKUHML44Eeuk4pNB4Zwu1A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vu6CA744Eeuk4pNB4Zwu1A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vu6CBL44Eeuk4pNB4Zwu1A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vu6CAb44Eeuk4pNB4Zwu1A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vu6CAr44Eeuk4pNB4Zwu1A" points="[0, 2, -174, -5]$[170, -8, -4, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vu7QIL44Eeuk4pNB4Zwu1A" id="(1.0,0.40789473684210525)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
