<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_N7KLsMihEeuhkK1zj21ppg" name="ValidateInterventions" author="andre" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_N7KLscihEeuhkK1zj21ppg" name="Validate Interventions">
      <elements xmi:type="process:Lane" xmi:id="_N7KLssihEeuhkK1zj21ppg" name="Gestor de Serviço" actor="_ZVe58MihEeuhkK1zj21ppg">
        <elements xmi:type="process:Task" xmi:id="_N7KLt8ihEeuhkK1zj21ppg" name="Valida se todos os técnicos lancaram as intervencoes" outgoing="_N9G3AMiiEeuhkK1zj21ppg" incoming="_6Jo3EMiiEeuhkK1zj21ppg _DM9fcMioEeuhkK1zj21ppg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_N7KLuMihEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_N7KLucihEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_N7KLusihEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_sE49AMreEeuaeM3KWOaS0Q" name="Month Interventions" definitionId="salesforce-querysobjects" event="ON_ENTER" definitionVersion="1.0.1">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_sE49AcreEeuaeM3KWOaS0Q" definitionId="salesforce-querysobjects" version="1.0.1" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49AsreEeuaeM3KWOaS0Q" key="username">
                <expression xmi:type="expression:Expression" xmi:id="_sE49A8reEeuaeM3KWOaS0Q" name="andre@ipl.com" content="andre@ipl.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49BMreEeuaeM3KWOaS0Q" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_sE49BcreEeuaeM3KWOaS0Q" name="janela2012" content="janela2012" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49BsreEeuaeM3KWOaS0Q" key="securityToken">
                <expression xmi:type="expression:Expression" xmi:id="_sE49B8reEeuaeM3KWOaS0Q" name="78HnE36tf0FEPzNFPjz7OEe2" content="78HnE36tf0FEPzNFPjz7OEe2" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49CMreEeuaeM3KWOaS0Q" key="authEndpoint">
                <expression xmi:type="expression:Expression" xmi:id="_sE49CcreEeuaeM3KWOaS0Q" name="https://login.salesforce.com/services/Soap/u/24.0" content="https://login.salesforce.com/services/Soap/u/24.0" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49CsreEeuaeM3KWOaS0Q" key="serviceEndpoint">
                <expression xmi:type="expression:Expression" xmi:id="_sE49C8reEeuaeM3KWOaS0Q" name="https://login.salesforce.com/services/Soap/u/24.0" content="https://login.salesforce.com/services/Soap/u/24.0" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49DMreEeuaeM3KWOaS0Q" key="restEndpoint">
                <expression xmi:type="expression:Expression" xmi:id="_sE49DcreEeuaeM3KWOaS0Q" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49DsreEeuaeM3KWOaS0Q" key="proxyHost">
                <expression xmi:type="expression:Expression" xmi:id="_sE49D8reEeuaeM3KWOaS0Q" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49EMreEeuaeM3KWOaS0Q" key="proxyPort">
                <expression xmi:type="expression:Expression" xmi:id="_sE49EcreEeuaeM3KWOaS0Q" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49EsreEeuaeM3KWOaS0Q" key="proxyUsername">
                <expression xmi:type="expression:Expression" xmi:id="_sE49E8reEeuaeM3KWOaS0Q" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49FMreEeuaeM3KWOaS0Q" key="proxyPassword">
                <expression xmi:type="expression:Expression" xmi:id="_sE49FcreEeuaeM3KWOaS0Q" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49FsreEeuaeM3KWOaS0Q" key="connectionTimeout">
                <expression xmi:type="expression:Expression" xmi:id="_sE49F8reEeuaeM3KWOaS0Q" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49GMreEeuaeM3KWOaS0Q" key="readTimeout">
                <expression xmi:type="expression:Expression" xmi:id="_sE49GcreEeuaeM3KWOaS0Q" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sE49GsreEeuaeM3KWOaS0Q" key="query">
                <expression xmi:type="expression:Expression" xmi:id="_sE49G8reEeuaeM3KWOaS0Q" name="&lt;pattern-expression>" content="SELECT Subject, ActivityDate FROM Task WHERE ActivityDate > LAST_MONTH" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_sE49HMreEeuaeM3KWOaS0Q">
              <leftOperand xmi:type="expression:Expression" xmi:id="_sE49HcreEeuaeM3KWOaS0Q" name="interventions" content="interventions" type="TYPE_VARIABLE" returnType="java.util.List">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zqxwUMreEeuaeM3KWOaS0Q" name="interventions" multiple="true" dataType="_N7KL5MihEeuhkK1zj21ppg" className="com.prestaser.model.Intervention"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_sE49HsreEeuaeM3KWOaS0Q" name="newScript()" content="import com.sforce.soap.partner.sobject.SObject&#xD;&#xA;import com.prestaser.model.Intervention&#xD;&#xA;import java.time.*&#xD;&#xA;&#xD;&#xA;ArrayList&lt;Intervention> accs = new ArrayList()&#xD;&#xA;&#xD;&#xA;SObject[] all = queryResults.getRecords()&#xD;&#xA;&#xD;&#xA;for  (SObject s in all){&#xD;&#xA;&#x9;Intervention a = new Intervention()&#xD;&#xA;&#x9;a.description = s.getField(&quot;Subject&quot;)&#xD;&#xA;&#x9;Date date = Date.parse(&quot;yyyy-MM-dd&quot;, s.getField(&quot;ActivityDate&quot;));&#xD;&#xA;&#x9;a.interventionDate = Instant.ofEpochMilli(date.getTime()).atZone(ZoneId.systemDefault()).toLocalDateTime();&#xD;&#xA;&#x9;accs.add(a)&#xD;&#xA;}&#xD;&#xA;return accs" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
                <referencedElements xmi:type="definition:Output" xmi:id="_zqyXYMreEeuaeM3KWOaS0Q" name="queryResults" type="com.sforce.soap.partner.QueryResult"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_sE49IMreEeuaeM3KWOaS0Q" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_TGoVkMiiEeuhkK1zj21ppg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_TGoVkciiEeuhkK1zj21ppg" name="allInterventionsValidated" content="allInterventionsValidated" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_TikDoMiiEeuhkK1zj21ppg" name="allInterventionsValidated" dataType="_N7KL3MihEeuhkK1zj21ppg"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_TGoVksiiEeuhkK1zj21ppg" name="checkIfAllInterventionsValidated()" content="if (allInterventionsValidatedInput == &quot;Sim&quot;) return true else return false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_OKE0oMilEeuhkK1zj21ppg" name="allInterventionsValidatedInput">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_OKE0ocilEeuhkK1zj21ppg"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_TGoVk8iiEeuhkK1zj21ppg" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_N7KLu8ihEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_N7KLvMihEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_N7KLvcihEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_N7KLvsihEeuhkK1zj21ppg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_N7KLv8ihEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_N7KLwMihEeuhkK1zj21ppg">
            <targetForm xmi:type="expression:Expression" xmi:id="_ZQN4EMikEeuhkK1zj21ppg" name="validateInterventions" content="508bcb28-a46f-4e84-92b7-a39b944120bc" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_N7KLwsihEeuhkK1zj21ppg">
            <inputs xmi:type="process:ContractInput" xmi:id="_DdPegMilEeuhkK1zj21ppg" name="allInterventionsValidatedInput">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_DdPegcilEeuhkK1zj21ppg"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_N7KLw8ihEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_4qE-QMihEeuhkK1zj21ppg" name="Notifica área de contabilidade" outgoing="_8k_7sMihEeuhkK1zj21ppg" incoming="_On_AAMiiEeuhkK1zj21ppg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4qGMYMihEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4qFlUMihEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4qGMYcihEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_mGU5wMiiEeuhkK1zj21ppg" name="Notifica area contabilidade" definitionId="email" event="ON_FINISH" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_mGU5wciiEeuhkK1zj21ppg" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU5wsiiEeuhkK1zj21ppg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_mGU5w8iiEeuhkK1zj21ppg" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU5xMiiEeuhkK1zj21ppg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_mGU5xciiEeuhkK1zj21ppg" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU5xsiiEeuhkK1zj21ppg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_mGU5x8iiEeuhkK1zj21ppg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU5yMiiEeuhkK1zj21ppg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_mGU5yciiEeuhkK1zj21ppg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU5ysiiEeuhkK1zj21ppg" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_mGU5y8iiEeuhkK1zj21ppg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU5zMiiEeuhkK1zj21ppg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_mGU5zciiEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU5zsiiEeuhkK1zj21ppg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_mGU5z8iiEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU50MiiEeuhkK1zj21ppg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_mGU50ciiEeuhkK1zj21ppg" name="no-reply@prestaser.com" content="no-reply@prestaser.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU50siiEeuhkK1zj21ppg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_mGU508iiEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU51MiiEeuhkK1zj21ppg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_mGU51ciiEeuhkK1zj21ppg" name="jorge.funfinan@prestaser.com" content="jorge.funfinan@prestaser.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU51siiEeuhkK1zj21ppg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_mGU518iiEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU52MiiEeuhkK1zj21ppg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_mGU52ciiEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU52siiEeuhkK1zj21ppg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_mGU528iiEeuhkK1zj21ppg" name="Intervenções Validadas" content="Intervenções Validadas" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU53MiiEeuhkK1zj21ppg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_mGU53ciiEeuhkK1zj21ppg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU53siiEeuhkK1zj21ppg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_mGU538iiEeuhkK1zj21ppg" name="&lt;pattern-expression>" content="&lt;p>Seguem as interven&amp;ccedil;&amp;otilde;es j&amp;aacute; validadas para emiss&amp;atilde;o de fatura.&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU54MiiEeuhkK1zj21ppg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_mGU54ciiEeuhkK1zj21ppg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU54siiEeuhkK1zj21ppg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_mGU548iiEeuhkK1zj21ppg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU55MiiEeuhkK1zj21ppg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_mGU55ciiEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mGU55siiEeuhkK1zj21ppg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_mGU558iiEeuhkK1zj21ppg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4qGMYsihEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4qGMY8ihEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4qGMZMihEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4qGzccihEeuhkK1zj21ppg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4qGzcMihEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndMessageEvent" xmi:id="_7CZggMihEeuhkK1zj21ppg" name="Dá aval à área de contabilidade" incoming="_8k_7sMihEeuhkK1zj21ppg" outgoingMessages="_ehfZ4MijEeuhkK1zj21ppg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7CaHkcihEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7CaHkMihEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7CaHksihEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_ehVB0MijEeuhkK1zj21ppg" name="Da aval a contabilidade">
            <correlation xmi:type="process:Correlation" xmi:id="_ehVB0cijEeuhkK1zj21ppg">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_ehVB0sijEeuhkK1zj21ppg"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_ehVB08ijEeuhkK1zj21ppg" name="Emit Invoices" content="Emit Invoices" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_ehVB1MijEeuhkK1zj21ppg" name="Recebe notificacao" content="Recebe notificacao" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_ehVB1cijEeuhkK1zj21ppg"/>
          </events>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_L6v9sMiiEeuhkK1zj21ppg" name="Todas as intervenções validadas?" outgoing="_On_AAMiiEeuhkK1zj21ppg _tiyEQMiiEeuhkK1zj21ppg" incoming="_N9G3AMiiEeuhkK1zj21ppg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L6wkwciiEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L6wkwMiiEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L6wkwsiiEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_wLS-oMiiEeuhkK1zj21ppg" name="Notifica técnicos para lançarem intervenções" outgoing="_5OoAUMiiEeuhkK1zj21ppg" incoming="_tiyEQMiiEeuhkK1zj21ppg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oYPSAciiEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oYPSAMiiEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oYPSAsiiEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_oYPSA8iiEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_oYP5EMiiEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oYP5EciiEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_oYP5E8iiEeuhkK1zj21ppg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_oYP5EsiiEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_5OWTgMiiEeuhkK1zj21ppg" name="Espera 2 horas" outgoing="_6Jo3EMiiEeuhkK1zj21ppg" incoming="_5OoAUMiiEeuhkK1zj21ppg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5OXhociiEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5OXhoMiiEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5OXhosiiEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_99bRwMiiEeuhkK1zj21ppg" name="02:00:00" content="7200000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_C6U3UMioEeuhkK1zj21ppg" name="Start1" outgoing="_DM9fcMioEeuhkK1zj21ppg">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_ueqf4MixEeuhkK1zj21ppg" source="_uegH0MixEeuhkK1zj21ppg"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_C6YhscioEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_C6YhsMioEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_C6ZIwMioEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_uegH0MixEeuhkK1zj21ppg" text="Timed Start Event aqui.... e para a entrega/defesa?"/>
      </elements>
      <data xmi:type="process:Data" xmi:id="_KcvuoMiiEeuhkK1zj21ppg" name="allInterventionsValidated" dataType="_N7KL3MihEeuhkK1zj21ppg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_KcvuociiEeuhkK1zj21ppg" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_lnjGIMreEeuaeM3KWOaS0Q" name="interventions" multiple="true" dataType="_N7KL5MihEeuhkK1zj21ppg" className="com.prestaser.model.Intervention">
        <defaultValue xmi:type="expression:Expression" xmi:id="_lnjGIcreEeuaeM3KWOaS0Q" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_N7KLxMihEeuhkK1zj21ppg">
        <targetForm xmi:type="expression:Expression" xmi:id="_Yyll4MreEeuaeM3KWOaS0Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_N7KLxsihEeuhkK1zj21ppg">
        <targetForm xmi:type="expression:Expression" xmi:id="_N7KLx8ihEeuhkK1zj21ppg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8k_7sMihEeuhkK1zj21ppg" target="_7CZggMihEeuhkK1zj21ppg" source="_4qE-QMihEeuhkK1zj21ppg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8lAiwMihEeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_8lAiwcihEeuhkK1zj21ppg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_N9G3AMiiEeuhkK1zj21ppg" target="_L6v9sMiiEeuhkK1zj21ppg" source="_N7KLt8ihEeuhkK1zj21ppg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_N9HeEMiiEeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_N9HeEciiEeuhkK1zj21ppg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_On_AAMiiEeuhkK1zj21ppg" name="Sim" target="_4qE-QMihEeuhkK1zj21ppg" source="_L6v9sMiiEeuhkK1zj21ppg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_On_AAciiEeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_On_nEMiiEeuhkK1zj21ppg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tiyEQMiiEeuhkK1zj21ppg" name="Não" target="_wLS-oMiiEeuhkK1zj21ppg" source="_L6v9sMiiEeuhkK1zj21ppg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tiyrUMiiEeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_tiyrUciiEeuhkK1zj21ppg" name="allInterventionsValidated == false" content="allInterventionsValidated == false" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_EQr_kMijEeuhkK1zj21ppg" name="allInterventionsValidated" dataType="_N7KL3MihEeuhkK1zj21ppg">
            <defaultValue xmi:type="expression:Expression" xmi:id="_EQr_kcijEeuhkK1zj21ppg" name="true" content="true" returnType="java.lang.Boolean"/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5OoAUMiiEeuhkK1zj21ppg" target="_5OWTgMiiEeuhkK1zj21ppg" source="_wLS-oMiiEeuhkK1zj21ppg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5OonYMiiEeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_5OonYciiEeuhkK1zj21ppg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6Jo3EMiiEeuhkK1zj21ppg" target="_N7KLt8ihEeuhkK1zj21ppg" source="_5OWTgMiiEeuhkK1zj21ppg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6JpeIMiiEeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_6JpeIciiEeuhkK1zj21ppg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DM9fcMioEeuhkK1zj21ppg" target="_N7KLt8ihEeuhkK1zj21ppg" source="_C6U3UMioEeuhkK1zj21ppg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DM9fccioEeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_DM9fcsioEeuhkK1zj21ppg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_ZVe58MihEeuhkK1zj21ppg" name="GestorServico" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_N7KLzMihEeuhkK1zj21ppg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_N7KLzcihEeuhkK1zj21ppg">
        <name xmi:type="expression:Expression" xmi:id="_N7KLzsihEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_N7KLz8ihEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_N7KL0MihEeuhkK1zj21ppg">
        <name xmi:type="expression:Expression" xmi:id="_N7KL0cihEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_N7KL0sihEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_N7KL08ihEeuhkK1zj21ppg">
        <name xmi:type="expression:Expression" xmi:id="_N7KL1MihEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_N7KL1cihEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_N7KL1sihEeuhkK1zj21ppg">
        <name xmi:type="expression:Expression" xmi:id="_N7KL18ihEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_N7KL2MihEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_N7KL2cihEeuhkK1zj21ppg">
        <name xmi:type="expression:Expression" xmi:id="_N7KL2sihEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_N7KL28ihEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_GWxiUMijEeuhkK1zj21ppg" name="Emit Invoices">
      <elements xmi:type="process:Lane" xmi:id="_UAsUoMijEeuhkK1zj21ppg" name="Area de Contabilidade e Finanças" actor="_QbgWoMijEeuhkK1zj21ppg">
        <elements xmi:type="process:StartMessageEvent" xmi:id="_XNBGsMijEeuhkK1zj21ppg" name="Recebe notificacao" outgoing="_OSewcMiqEeuhkK1zj21ppg" event="Da aval a contabilidade" incomingMessag="_ehfZ4MijEeuhkK1zj21ppg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XNCU0MijEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XNBtwMijEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XNCU0cijEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_9DBCgMijEeuhkK1zj21ppg" name="Fatura Emitida" incoming="_QQ1dEMi2EeuhkK1zj21ppg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9DFT8cijEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9DFT8MijEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9DF7AMijEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_OSGV8MiqEeuhkK1zj21ppg" name="Retira listagem das intervenções" outgoing="_HYaD0Mi2EeuhkK1zj21ppg" incoming="_OSewcMiqEeuhkK1zj21ppg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OSNDociqEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OSNDoMiqEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OSNDosiqEeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_bfsJ4MiwEeuhkK1zj21ppg" name="Get month interventions" definitionId="salesforce-querysobjects" event="ON_ENTER" definitionVersion="1.0.1">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_bfsJ4ciwEeuhkK1zj21ppg" definitionId="salesforce-querysobjects" version="1.0.1" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ4siwEeuhkK1zj21ppg" key="username">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ48iwEeuhkK1zj21ppg" name="andre@ipl.com" content="andre@ipl.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ5MiwEeuhkK1zj21ppg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ5ciwEeuhkK1zj21ppg" name="janela2012" content="janela2012" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ5siwEeuhkK1zj21ppg" key="securityToken">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ58iwEeuhkK1zj21ppg" name="78HnE36tf0FEPzNFPjz7OEe2" content="78HnE36tf0FEPzNFPjz7OEe2" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ6MiwEeuhkK1zj21ppg" key="authEndpoint">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ6ciwEeuhkK1zj21ppg" name="https://login.salesforce.com/services/Soap/u/24.0" content="https://login.salesforce.com/services/Soap/u/24.0" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ6siwEeuhkK1zj21ppg" key="serviceEndpoint">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ68iwEeuhkK1zj21ppg" name="https://login.salesforce.com/services/Soap/u/24.0" content="https://login.salesforce.com/services/Soap/u/24.0" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ7MiwEeuhkK1zj21ppg" key="restEndpoint">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ7ciwEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ7siwEeuhkK1zj21ppg" key="proxyHost">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ78iwEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ8MiwEeuhkK1zj21ppg" key="proxyPort">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ8ciwEeuhkK1zj21ppg" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ8siwEeuhkK1zj21ppg" key="proxyUsername">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ88iwEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ9MiwEeuhkK1zj21ppg" key="proxyPassword">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ9ciwEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ9siwEeuhkK1zj21ppg" key="connectionTimeout">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ98iwEeuhkK1zj21ppg" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ-MiwEeuhkK1zj21ppg" key="readTimeout">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ-ciwEeuhkK1zj21ppg" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bfsJ-siwEeuhkK1zj21ppg" key="query">
                <expression xmi:type="expression:Expression" xmi:id="_bfsJ-8iwEeuhkK1zj21ppg" name="&lt;pattern-expression>" content="SELECT Subject, ActivityDate FROM Task WHERE ActivityDate > LAST_MONTH" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_bfsJ_MiwEeuhkK1zj21ppg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_bfsJ_ciwEeuhkK1zj21ppg" name="interventions" content="interventions" type="TYPE_VARIABLE" returnType="java.util.List">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_BIPfkMixEeuhkK1zj21ppg" name="interventions" multiple="true" dataType="_N7KL5MihEeuhkK1zj21ppg" className="com.prestaser.model.Intervention"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_bfsJ_siwEeuhkK1zj21ppg" name="getInterventions()" content="import com.sforce.soap.partner.sobject.SObject&#xD;&#xA;import com.prestaser.model.Intervention&#xD;&#xA;import java.time.*&#xD;&#xA;&#xD;&#xA;ArrayList&lt;Intervention> accs = new ArrayList()&#xD;&#xA;&#xD;&#xA;SObject[] all = queryResults.getRecords()&#xD;&#xA;&#xD;&#xA;for  (SObject s in all){&#xD;&#xA;&#x9;Intervention a = new Intervention()&#xD;&#xA;&#x9;a.description = s.getField(&quot;Subject&quot;)&#xD;&#xA;&#x9;Date date = Date.parse(&quot;yyyy-MM-dd&quot;, s.getField(&quot;ActivityDate&quot;));&#xD;&#xA;&#x9;a.interventionDate = Instant.ofEpochMilli(date.getTime()).atZone(ZoneId.systemDefault()).toLocalDateTime();&#xD;&#xA;&#x9;accs.add(a)&#xD;&#xA;}&#xD;&#xA;return accs" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
                <referencedElements xmi:type="definition:Output" xmi:id="_V94TkMojEeu3-eat168aag" name="queryResults" type="com.sforce.soap.partner.QueryResult"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_bfsKAMiwEeuhkK1zj21ppg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_2xk3IMn3Eeutlquhj76Hdw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2xk3Icn3Eeutlquhj76Hdw" name="interventionsCount" content="interventionsCount" type="TYPE_VARIABLE" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_wAf6AMn5Eeutlquhj76Hdw" name="interventionsCount" dataType="_N7KL3sihEeuhkK1zj21ppg"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2xk3Isn3Eeutlquhj76Hdw" name="getInterventionsCount()" content="return interventions.iterator().size()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_t3xS8Mn5Eeutlquhj76Hdw" name="interventions" multiple="true" dataType="_N7KL5MihEeuhkK1zj21ppg" className="com.prestaser.model.Intervention"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2xk3I8n3Eeutlquhj76Hdw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OSNDo8iqEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OSNqsMiqEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OSNqsciqEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_OSNqs8iqEeuhkK1zj21ppg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_OSNqssiqEeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_IOAPEMi2EeuhkK1zj21ppg" name="Emitir Faturas" outgoing="_PI7Z0Mi2EeuhkK1zj21ppg" incoming="_HYaD0Mi2EeuhkK1zj21ppg" type="STANDARD" testBefore="true">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EHjXEsi2EeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EHjXEci2EeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EHjXE8i2EeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_HKQEAMofEeu3-eat168aag" name="erp" definitionId="database-mysql" event="ON_FINISH" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_HKQrEMofEeu3-eat168aag" definitionId="database-mysql" version="1.0.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HKQrEcofEeu3-eat168aag" key="driver">
                <expression xmi:type="expression:Expression" xmi:id="_HKQrEsofEeu3-eat168aag" name="com.mysql.jdbc.Driver" content="com.mysql.jdbc.Driver" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HKQrE8ofEeu3-eat168aag" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_HKQrFMofEeu3-eat168aag" name="jdbc:mysql://127.0.0.1:3306/prestaser?serverTimezone=UTC" content="jdbc:mysql://127.0.0.1:3306/prestaser?serverTimezone=UTC" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HKQrFcofEeu3-eat168aag" key="script">
                <expression xmi:type="expression:Expression" xmi:id="_HKQrFsofEeu3-eat168aag" name="script()" content="&quot;INSERT INTO fatura (descricao, dataFatura, total) VALUES('&quot; + intName + &quot;','&quot; + intDate + &quot;','&quot; + 1000 + &quot;')&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_RqxDIMokEeu3-eat168aag" name="intName" dataType="_N7KL4cihEeuhkK1zj21ppg"/>
                  <referencedElements xmi:type="process:JavaObjectData" xmi:id="_RqxDIcokEeu3-eat168aag" name="intDate" dataType="_N7KL4sihEeuhkK1zj21ppg" className="java.time.LocalDateTime"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HKQrGcofEeu3-eat168aag" key="username">
                <expression xmi:type="expression:Expression" xmi:id="_HKQrGsofEeu3-eat168aag" name="root" content="root" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HKQrG8ofEeu3-eat168aag" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_HKQrHMofEeu3-eat168aag" name="root" content="root" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HKQrHcofEeu3-eat168aag" key="separator">
                <expression xmi:type="expression:Expression" xmi:id="_HKQrHsofEeu3-eat168aag" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HKQrH8ofEeu3-eat168aag" key="outputType">
                <expression xmi:type="expression:Expression" xmi:id="_HKQrIMofEeu3-eat168aag" name="outputType" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_HKQrIcofEeu3-eat168aag" key="wizardMode">
                <expression xmi:type="expression:Expression" xmi:id="_HKQrIsofEeu3-eat168aag" name="true" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
            </configuration>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_VjqrUMn4Eeutlquhj76Hdw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_VjqrUcn4Eeutlquhj76Hdw" name="intName" content="intName" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_V6QmYMn4Eeutlquhj76Hdw" name="intName" dataType="_N7KL4cihEeuhkK1zj21ppg"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_VjqrUsn4Eeutlquhj76Hdw" name="newScript()" content="interventions.getAt(iterator).description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_sjCNQMn8Eeutlquhj76Hdw" name="interventions" multiple="true" dataType="_N7KL5MihEeuhkK1zj21ppg" className="com.prestaser.model.Intervention"/>
              <referencedElements xmi:type="process:Data" xmi:id="_sjCNQcn8Eeutlquhj76Hdw" name="iterator" dataType="_N7KL3sihEeuhkK1zj21ppg"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_VjqrU8n4Eeutlquhj76Hdw" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_XjjfcMn4Eeutlquhj76Hdw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Xjjfccn4Eeutlquhj76Hdw" name="intDate" content="intDate" type="TYPE_VARIABLE" returnType="java.time.LocalDateTime">
              <referencedElements xmi:type="process:Data" xmi:id="_ZWYvAMn4Eeutlquhj76Hdw" name="intDate" dataType="_N7KL4sihEeuhkK1zj21ppg"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Xjjfcsn4Eeutlquhj76Hdw" name="newScript()" content="interventions.getAt(iterator).interventionDate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDateTime">
              <referencedElements xmi:type="process:Data" xmi:id="_8y3AIMojEeu3-eat168aag" name="iterator" dataType="_N7KL3sihEeuhkK1zj21ppg"/>
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8y3AIcojEeu3-eat168aag" name="interventions" multiple="true" dataType="_N7KL5MihEeuhkK1zj21ppg" className="com.prestaser.model.Intervention"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Xjjfc8n4Eeutlquhj76Hdw" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_ugyFoMn3Eeutlquhj76Hdw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ugyFocn3Eeutlquhj76Hdw" name="iterator" content="iterator" type="TYPE_VARIABLE" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_vBC6EMn3Eeutlquhj76Hdw" name="iterator" dataType="_N7KL3sihEeuhkK1zj21ppg"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ugyFosn3Eeutlquhj76Hdw" name="incIterator()" content="iterator+1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_w0i4AMn3Eeutlquhj76Hdw" name="iterator" dataType="_N7KL3sihEeuhkK1zj21ppg"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ugyFo8n3Eeutlquhj76Hdw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EHjXFMi2EeuhkK1zj21ppg" name="loopWhile()" content="iterator &lt; interventionsCount" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
            <referencedElements xmi:type="process:Data" xmi:id="_zNOUsMn5Eeutlquhj76Hdw" name="iterator" dataType="_N7KL3sihEeuhkK1zj21ppg"/>
            <referencedElements xmi:type="process:Data" xmi:id="_zNOUscn5Eeutlquhj76Hdw" name="interventionsCount" dataType="_N7KL3sihEeuhkK1zj21ppg"/>
          </loopCondition>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EHjXFci2EeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EHjXFsi2EeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EHjXGMi2EeuhkK1zj21ppg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EHjXF8i2EeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_N8y94Mi2EeuhkK1zj21ppg" name="Enviar faturas" outgoing="_QQ1dEMi2EeuhkK1zj21ppg" incoming="_PI7Z0Mi2EeuhkK1zj21ppg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MLIzAci2EeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MLIzAMi2EeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MLIzAsi2EeuhkK1zj21ppg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_b12_cMi2EeuhkK1zj21ppg" name="Notificar envio de fatura" definitionId="email" event="ON_FINISH" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_b12_cci2EeuhkK1zj21ppg" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_csi2EeuhkK1zj21ppg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_b12_c8i2EeuhkK1zj21ppg" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_dMi2EeuhkK1zj21ppg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_b12_dci2EeuhkK1zj21ppg" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_dsi2EeuhkK1zj21ppg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_b12_d8i2EeuhkK1zj21ppg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_eMi2EeuhkK1zj21ppg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_b12_eci2EeuhkK1zj21ppg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_esi2EeuhkK1zj21ppg" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_b12_e8i2EeuhkK1zj21ppg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_fMi2EeuhkK1zj21ppg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_b12_fci2EeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_fsi2EeuhkK1zj21ppg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_b12_f8i2EeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_gMi2EeuhkK1zj21ppg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_b12_gci2EeuhkK1zj21ppg" name="no-reply@prestaser.com" content="no-reply@prestaser.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_gsi2EeuhkK1zj21ppg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_b12_g8i2EeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_hMi2EeuhkK1zj21ppg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_b12_hci2EeuhkK1zj21ppg" name="cliente@cliente.com" content="cliente@cliente.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_hsi2EeuhkK1zj21ppg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_b12_h8i2EeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_iMi2EeuhkK1zj21ppg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_b12_ici2EeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_isi2EeuhkK1zj21ppg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_b12_i8i2EeuhkK1zj21ppg" name="Faturas Emitidas e Enviadas" content="Faturas Emitidas e Enviadas" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_jMi2EeuhkK1zj21ppg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_b12_jci2EeuhkK1zj21ppg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_jsi2EeuhkK1zj21ppg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_b12_j8i2EeuhkK1zj21ppg" name="&lt;pattern-expression>" content="&lt;p>As faturas relativas a si foram emitidas e enviadas por correio.&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_kMi2EeuhkK1zj21ppg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_b12_kci2EeuhkK1zj21ppg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_ksi2EeuhkK1zj21ppg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_b12_k8i2EeuhkK1zj21ppg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_lMi2EeuhkK1zj21ppg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_b12_lci2EeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_b12_lsi2EeuhkK1zj21ppg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_b12_l8i2EeuhkK1zj21ppg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_MLIzA8i2EeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_MLIzBMi2EeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_MLIzBci2EeuhkK1zj21ppg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_MLIzB8i2EeuhkK1zj21ppg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_MLIzBsi2EeuhkK1zj21ppg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_z6XJAMiwEeuhkK1zj21ppg" name="interventions" multiple="true" dataType="_N7KL5MihEeuhkK1zj21ppg" className="com.prestaser.model.Intervention">
        <defaultValue xmi:type="expression:Expression" xmi:id="_z6XJAciwEeuhkK1zj21ppg" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_gXHcQMn3Eeutlquhj76Hdw" name="intervention" dataType="_N7KL5MihEeuhkK1zj21ppg" className="com.prestaser.model.Intervention">
        <defaultValue xmi:type="expression:Expression" xmi:id="_gXHcQcn3Eeutlquhj76Hdw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_iDA9YMn3Eeutlquhj76Hdw" name="iterator" dataType="_N7KL3sihEeuhkK1zj21ppg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_iDA9Ycn3Eeutlquhj76Hdw" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2FQjsMn3Eeutlquhj76Hdw" name="interventionsCount" dataType="_N7KL3sihEeuhkK1zj21ppg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_2FQjscn3Eeutlquhj76Hdw" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_I-nPUMn4Eeutlquhj76Hdw" name="intName" dataType="_N7KL4cihEeuhkK1zj21ppg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_I-nPUcn4Eeutlquhj76Hdw" content=""/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_rolFQMn-Eeutlquhj76Hdw" name="intDate" dataType="_N7KL4sihEeuhkK1zj21ppg" className="java.time.LocalDateTime">
        <defaultValue xmi:type="expression:Expression" xmi:id="_rolFQcn-Eeutlquhj76Hdw" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDateTime"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_GWywcMijEeuhkK1zj21ppg">
        <targetForm xmi:type="expression:Expression" xmi:id="_YqVBwMreEeuaeM3KWOaS0Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_GWywcsijEeuhkK1zj21ppg">
        <targetForm xmi:type="expression:Expression" xmi:id="_GWywc8ijEeuhkK1zj21ppg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OSewcMiqEeuhkK1zj21ppg" target="_OSGV8MiqEeuhkK1zj21ppg" source="_XNBGsMijEeuhkK1zj21ppg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OSfXgMiqEeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OSfXgciqEeuhkK1zj21ppg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HYaD0Mi2EeuhkK1zj21ppg" target="_IOAPEMi2EeuhkK1zj21ppg" source="_OSGV8MiqEeuhkK1zj21ppg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HYaD0ci2EeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_HYaD0si2EeuhkK1zj21ppg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PI7Z0Mi2EeuhkK1zj21ppg" target="_N8y94Mi2EeuhkK1zj21ppg" source="_IOAPEMi2EeuhkK1zj21ppg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PI7Z0ci2EeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_PI7Z0si2EeuhkK1zj21ppg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QQ1dEMi2EeuhkK1zj21ppg" target="_9DBCgMijEeuhkK1zj21ppg" source="_N8y94Mi2EeuhkK1zj21ppg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QQ1dEci2EeuhkK1zj21ppg"/>
        <condition xmi:type="expression:Expression" xmi:id="_QQ1dEsi2EeuhkK1zj21ppg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_QbgWoMijEeuhkK1zj21ppg" name="Area Contabilidade e Financas" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_GWywdMijEeuhkK1zj21ppg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_GWyJYMijEeuhkK1zj21ppg">
        <name xmi:type="expression:Expression" xmi:id="_GWyJYcijEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_GWyJYsijEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_GWyJY8ijEeuhkK1zj21ppg">
        <name xmi:type="expression:Expression" xmi:id="_GWyJZMijEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_GWyJZcijEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_GWyJZsijEeuhkK1zj21ppg">
        <name xmi:type="expression:Expression" xmi:id="_GWyJZ8ijEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_GWyJaMijEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_GWyJacijEeuhkK1zj21ppg">
        <name xmi:type="expression:Expression" xmi:id="_GWyJasijEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_GWyJa8ijEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_GWyJbMijEeuhkK1zj21ppg">
        <name xmi:type="expression:Expression" xmi:id="_GWyJbcijEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_GWyJbsijEeuhkK1zj21ppg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_N7KL3MihEeuhkK1zj21ppg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_N7KL3cihEeuhkK1zj21ppg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_N7KL3sihEeuhkK1zj21ppg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_N7KL38ihEeuhkK1zj21ppg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_N7KL4MihEeuhkK1zj21ppg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_N7KL4cihEeuhkK1zj21ppg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_N7KL4sihEeuhkK1zj21ppg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_N7KL48ihEeuhkK1zj21ppg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_N7KL5MihEeuhkK1zj21ppg" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_ehfZ4MijEeuhkK1zj21ppg" name="Da aval a contabilidade" target="_XNBGsMijEeuhkK1zj21ppg" source="_7CZggMihEeuhkK1zj21ppg"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_N7KL5cihEeuhkK1zj21ppg" type="Process" element="_N7KLsMihEeuhkK1zj21ppg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_N7KL5sihEeuhkK1zj21ppg" type="2007" element="_N7KLscihEeuhkK1zj21ppg">
      <children xmi:type="notation:DecorationNode" xmi:id="_N7KL58ihEeuhkK1zj21ppg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_N7KL6MihEeuhkK1zj21ppg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_N7KL6cihEeuhkK1zj21ppg" type="3007" element="_N7KLssihEeuhkK1zj21ppg">
          <children xmi:type="notation:DecorationNode" xmi:id="_N7KL6sihEeuhkK1zj21ppg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_N7KL68ihEeuhkK1zj21ppg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_N7KL7MihEeuhkK1zj21ppg" type="3005" element="_N7KLt8ihEeuhkK1zj21ppg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_N7KL7cihEeuhkK1zj21ppg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_N7KL7sihEeuhkK1zj21ppg" x="249" y="66" width="213" height="106"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4qKd0MihEeuhkK1zj21ppg" type="3027" element="_4qE-QMihEeuhkK1zj21ppg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4qLE4MihEeuhkK1zj21ppg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4qKd0cihEeuhkK1zj21ppg" x="782" y="64" width="191" height="95"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7Ccj0MihEeuhkK1zj21ppg" type="3011" element="_7CZggMihEeuhkK1zj21ppg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_7CdK4MihEeuhkK1zj21ppg" type="5028">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_7Cdx8MihEeuhkK1zj21ppg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7Ccj0cihEeuhkK1zj21ppg" x="1094" y="97"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L6zBAMiiEeuhkK1zj21ppg" type="3008" element="_L6v9sMiiEeuhkK1zj21ppg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_L6zoEMiiEeuhkK1zj21ppg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_L6zoEciiEeuhkK1zj21ppg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L6zBAciiEeuhkK1zj21ppg" x="566" y="97"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wLUz0MiiEeuhkK1zj21ppg" type="3027" element="_wLS-oMiiEeuhkK1zj21ppg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wLVa4MiiEeuhkK1zj21ppg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wLUz0ciiEeuhkK1zj21ppg" x="493" y="234" width="189" height="94"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5OZ94MiiEeuhkK1zj21ppg" type="3017" element="_5OWTgMiiEeuhkK1zj21ppg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5Oak8MiiEeuhkK1zj21ppg" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5Oak8ciiEeuhkK1zj21ppg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5OZ94ciiEeuhkK1zj21ppg" x="350" y="266"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_C6aW4MioEeuhkK1zj21ppg" type="3002" element="_C6U3UMioEeuhkK1zj21ppg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_C6a98MioEeuhkK1zj21ppg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_C6a98cioEeuhkK1zj21ppg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_C6aW4cioEeuhkK1zj21ppg" x="110" y="104"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_ueh9AMixEeuhkK1zj21ppg" type="3015" element="_uegH0MixEeuhkK1zj21ppg">
              <children xmi:type="notation:DecorationNode" xmi:id="_ueikEMixEeuhkK1zj21ppg" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_ueh9AcixEeuhkK1zj21ppg"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_ueh9AsixEeuhkK1zj21ppg" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_ueh9A8ixEeuhkK1zj21ppg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ueh9BMixEeuhkK1zj21ppg" x="53" y="10" width="176" height="74"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_N7KL88ihEeuhkK1zj21ppg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_N7KL9MihEeuhkK1zj21ppg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_N7KL9cihEeuhkK1zj21ppg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_N7KL9sihEeuhkK1zj21ppg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_N7KL98ihEeuhkK1zj21ppg" x="53" y="10" width="1292" height="388"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_N7KL-MihEeuhkK1zj21ppg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_N7KL-cihEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_N7KL-sihEeuhkK1zj21ppg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_N7KL-8ihEeuhkK1zj21ppg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_N7KL_MihEeuhkK1zj21ppg" width="1320" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_GW0loMijEeuhkK1zj21ppg" type="2007" element="_GWxiUMijEeuhkK1zj21ppg">
      <children xmi:type="notation:DecorationNode" xmi:id="_GW1zwMijEeuhkK1zj21ppg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_GW1zwcijEeuhkK1zj21ppg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_UAuJ0MijEeuhkK1zj21ppg" type="3007" element="_UAsUoMijEeuhkK1zj21ppg">
          <children xmi:type="notation:DecorationNode" xmi:id="_UAuw4MijEeuhkK1zj21ppg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_UAuw4cijEeuhkK1zj21ppg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_XNEKAMijEeuhkK1zj21ppg" type="3012" element="_XNBGsMijEeuhkK1zj21ppg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XNExEMijEeuhkK1zj21ppg" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XNExEcijEeuhkK1zj21ppg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XNEKAcijEeuhkK1zj21ppg" x="84" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9DJlYMijEeuhkK1zj21ppg" type="3003" element="_9DBCgMijEeuhkK1zj21ppg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_9DKMcMijEeuhkK1zj21ppg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_9DKzgMijEeuhkK1zj21ppg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9DJlYcijEeuhkK1zj21ppg" x="926" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OSQuAMiqEeuhkK1zj21ppg" type="3027" element="_OSGV8MiqEeuhkK1zj21ppg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OSR8IMiqEeuhkK1zj21ppg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OSQuAciqEeuhkK1zj21ppg" x="218" y="90" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IOA2IMi2EeuhkK1zj21ppg" type="3027" element="_IOAPEMi2EeuhkK1zj21ppg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IOA2Isi2EeuhkK1zj21ppg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IOA2Ici2EeuhkK1zj21ppg" x="470" y="91" width="136" height="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_N8zk-Mi2EeuhkK1zj21ppg" type="3027" element="_N8y94Mi2EeuhkK1zj21ppg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_N8zk-si2EeuhkK1zj21ppg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_N8zk-ci2EeuhkK1zj21ppg" x="710" y="88" width="148" height="74"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_UAuJ0cijEeuhkK1zj21ppg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_UAuJ0sijEeuhkK1zj21ppg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_UAuJ08ijEeuhkK1zj21ppg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_UAuw4sijEeuhkK1zj21ppg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UAuJ1MijEeuhkK1zj21ppg" x="208" y="127"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_GW0locijEeuhkK1zj21ppg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_GW0losijEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_GW0lo8ijEeuhkK1zj21ppg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_GW1zwsijEeuhkK1zj21ppg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GW0lpMijEeuhkK1zj21ppg" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_N7KL_cihEeuhkK1zj21ppg"/>
    <edges xmi:type="notation:Connector" xmi:id="_8lCX8MihEeuhkK1zj21ppg" type="4001" element="_8k_7sMihEeuhkK1zj21ppg" source="_4qKd0MihEeuhkK1zj21ppg" target="_7Ccj0MihEeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8lC_AMihEeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8lDmEMihEeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8lCX8cihEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8lCX8sihEeuhkK1zj21ppg" points="[0, 10, -224, -1]$[218, 10, -6, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8lKTwMihEeuhkK1zj21ppg" id="(1.0,0.3157894736842105)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8lKTwcihEeuhkK1zj21ppg" id="(0.23333333333333334,0.26666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_N9IsMMiiEeuhkK1zj21ppg" type="4001" element="_N9G3AMiiEeuhkK1zj21ppg" source="_N7KL7MihEeuhkK1zj21ppg" target="_L6zBAMiiEeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_N9IsM8iiEeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_N9JTQMiiEeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_N9IsMciiEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_N9IsMsiiEeuhkK1zj21ppg" points="[0, 23, -125, 0]$[104, 23, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N9MWkMiiEeuhkK1zj21ppg" id="(1.0,0.27358490566037735)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OoA1MMiiEeuhkK1zj21ppg" type="4001" element="_On_AAMiiEeuhkK1zj21ppg" source="_L6zBAMiiEeuhkK1zj21ppg" target="_4qKd0MihEeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OoBcQMiiEeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OoCDUMiiEeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OoA1MciiEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OoA1MsiiEeuhkK1zj21ppg" points="[0, -7, -208, 8]$[173, -7, -35, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OoHi4MiiEeuhkK1zj21ppg" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OoHi4ciiEeuhkK1zj21ppg" id="(0.18324607329842932,0.4842105263157895)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tjQlYMiiEeuhkK1zj21ppg" type="4001" element="_tiyEQMiiEeuhkK1zj21ppg" source="_L6zBAMiiEeuhkK1zj21ppg" target="_wLUz0MiiEeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tjRMcMiiEeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tjRMcciiEeuhkK1zj21ppg" y="-34"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tjQlYciiEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tjQlYsiiEeuhkK1zj21ppg" points="[-22, 17, 14, -114]$[-22, 111, 14, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tjX6IMiiEeuhkK1zj21ppg" id="(1.0,0.6046511627906976)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tjYhMMiiEeuhkK1zj21ppg" id="(0.42328042328042326,0.2127659574468085)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5Op1gMiiEeuhkK1zj21ppg" type="4001" element="_5OoAUMiiEeuhkK1zj21ppg" source="_wLUz0MiiEeuhkK1zj21ppg" target="_5OZ94MiiEeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5OrDoMiiEeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5OrDociiEeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5Op1gciiEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5Op1gsiiEeuhkK1zj21ppg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6JrTUMiiEeuhkK1zj21ppg" type="4001" element="_6Jo3EMiiEeuhkK1zj21ppg" source="_5OZ94MiiEeuhkK1zj21ppg" target="_N7KL7MihEeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6Jr6YMiiEeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6Jr6YciiEeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6JrTUciiEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6JrTUsiiEeuhkK1zj21ppg" points="[-15, -30, 58, 147]$[-77, -124, -4, 53]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6JxZ8MiiEeuhkK1zj21ppg" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ehgoAMijEeuhkK1zj21ppg" type="4002" element="_ehfZ4MijEeuhkK1zj21ppg" source="_7Ccj0MihEeuhkK1zj21ppg" target="_XNEKAMijEeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ehhPEMijEeuhkK1zj21ppg" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ehh2IMijEeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ehgoAcijEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ehgoAsijEeuhkK1zj21ppg" points="[0, 14, 1010, -407]$[0, 242, 1010, -179]$[-999, 242, 11, -179]$[-999, 411, 11, -10]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DM-tkMioEeuhkK1zj21ppg" type="4001" element="_DM9fcMioEeuhkK1zj21ppg" source="_C6aW4MioEeuhkK1zj21ppg" target="_N7KL7MihEeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DM_UoMioEeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DM_UocioEeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DM-tkcioEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DM-tksioEeuhkK1zj21ppg" points="[-3, -24, -134, 99]$[104, -118, -27, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DNCX8MioEeuhkK1zj21ppg" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DNCX8cioEeuhkK1zj21ppg" id="(0.1267605633802817,0.660377358490566)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OSgloMiqEeuhkK1zj21ppg" type="4001" element="_OSewcMiqEeuhkK1zj21ppg" source="_XNEKAMijEeuhkK1zj21ppg" target="_OSQuAMiqEeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OShzwMiqEeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OShzwciqEeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OSglociqEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OSglosiqEeuhkK1zj21ppg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ueruAMixEeuhkK1zj21ppg" type="4003" element="_ueqf4MixEeuhkK1zj21ppg" source="_ueh9AMixEeuhkK1zj21ppg" target="_C6aW4MioEeuhkK1zj21ppg">
      <styles xmi:type="notation:FontStyle" xmi:id="_ueruAcixEeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ueruAsixEeuhkK1zj21ppg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HYaD08i2EeuhkK1zj21ppg" type="4001" element="_HYaD0Mi2EeuhkK1zj21ppg" source="_OSQuAMiqEeuhkK1zj21ppg" target="_IOA2IMi2EeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HYaq4Mi2EeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HYaq4ci2EeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HYaD1Mi2EeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HYaD1ci2EeuhkK1zj21ppg" points="[0, 1, -124, 0]$[116, -1, -8, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HYb5AMi2EeuhkK1zj21ppg" id="(1.0,0.3875)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HYb5Aci2EeuhkK1zj21ppg" id="(0.058823529411764705,0.38235294117647056)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PI7Z08i2EeuhkK1zj21ppg" type="4001" element="_PI7Z0Mi2EeuhkK1zj21ppg" source="_IOA2IMi2EeuhkK1zj21ppg" target="_N8zk-Mi2EeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PI7Z1si2EeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PI8A4Mi2EeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PI7Z1Mi2EeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PI7Z1ci2EeuhkK1zj21ppg" points="[0, 2, -119, 0]$[104, 1, -15, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PI9PAMi2EeuhkK1zj21ppg" id="(1.0,0.45588235294117646)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PI9PAci2EeuhkK1zj21ppg" id="(0.125,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QQ2EIMi2EeuhkK1zj21ppg" type="4001" element="_QQ1dEMi2EeuhkK1zj21ppg" source="_N8zk-Mi2EeuhkK1zj21ppg" target="_9DJlYMijEeuhkK1zj21ppg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QQ2EI8i2EeuhkK1zj21ppg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QQ2EJMi2EeuhkK1zj21ppg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QQ2EIci2EeuhkK1zj21ppg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QQ2EIsi2EeuhkK1zj21ppg" points="[0, 0, -59, -9]$[59, 23, 0, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QQ2rMMi2EeuhkK1zj21ppg" id="(1.0,0.43243243243243246)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
